/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as http from "../http";
import type * as predictedMetrics from "../predictedMetrics";
import type * as recommendedTasks from "../recommendedTasks";
import type * as schedule_tasks from "../schedule_tasks";
import type * as sleepScores from "../sleepScores";
import type * as stressScores from "../stressScores";
import type * as tasks from "../tasks";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  http: typeof http;
  predictedMetrics: typeof predictedMetrics;
  recommendedTasks: typeof recommendedTasks;
  schedule_tasks: typeof schedule_tasks;
  sleepScores: typeof sleepScores;
  stressScores: typeof stressScores;
  tasks: typeof tasks;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
